version: "3.7"

x-zimagi: &zimagi
    image: ${ZIMAGI_DEFAULT_RUNTIME_IMAGE}
    restart: always
    env_file: .env
    volumes:
        - "${ZIMAGI_LIB_DIRECTORY}:/usr/local/lib/zimagi"

services:
    data-api:
        <<: *zimagi
        entrypoint: zimagi-data
        ports:
            - "${ZIMAGI_DATA_PORT}:${ZIMAGI_DATA_PORT}"
