version: "3.7"

x-zimagi: &zimagi
    image: ${ZIMAGI_DEFAULT_RUNTIME_IMAGE}
    restart: always
    environment:
        ZIMAGI_POSTGRES_HOST: data
        ZIMAGI_POSTGRES_PORT: 5432
        ZIMAGI_REDIS_HOST: objects
        ZIMAGI_REDIS_PORT: 6379
    env_file: .env
    volumes:
        - "${ZIMAGI_LIB_DIRECTORY}:/usr/local/lib/zimagi"
    depends_on:
        - data
        - objects

services:
    command-api:
        <<: *zimagi
        entrypoint: zimagi-command
        ports:
            - "${ZIMAGI_COMMAND_PORT}:${ZIMAGI_COMMAND_PORT}"

    data-api:
        <<: *zimagi
        entrypoint: zimagi-data
        ports:
            - "${ZIMAGI_DATA_PORT}:${ZIMAGI_DATA_PORT}"

    scheduler:
        <<: *zimagi
        entrypoint: zimagi-scheduler

    worker:
        <<: *zimagi
        entrypoint: zimagi-worker

    data:
        image: postgres:12
        command: postgres -c 'max_connections=100'
        restart: always
        environment:
            POSTGRES_USER: ${ZIMAGI_POSTGRES_USER}
            POSTGRES_PASSWORD: ${ZIMAGI_POSTGRES_PASSWORD}
            POSTGRES_DB: ${ZIMAGI_POSTGRES_DB}
        volumes:
            - app-data:/var/lib/postgresql
        ports:
            - "5432:5432"

    objects:
        image: redis:5
        restart: always
        command: redis-server --requirepass ${ZIMAGI_REDIS_PASSWORD}
        volumes:
            - app-objects:/data
        ports:
            - "6379:6379"

volumes:
    app-data:
        external: false

    app-objects:
        external: false