version: "3.7"

x-zimagi: &zimagi
    image: ${ZIMAGI_DEFAULT_RUNTIME_IMAGE}
    restart: always
    env_file: .env
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "${ZIMAGI_LIB_DIRECTORY}:/usr/local/lib/zimagi"

services:
    command-api:
        <<: *zimagi
        entrypoint: zimagi-command
        ports:
            - "${ZIMAGI_COMMAND_PORT}:${ZIMAGI_COMMAND_PORT}"

    data-api:
        <<: *zimagi
        entrypoint: zimagi-data
        ports:
            - "${ZIMAGI_DATA_PORT}:${ZIMAGI_DATA_PORT}"

    scheduler:
        <<: *zimagi
        entrypoint: zimagi-scheduler

    worker:
        <<: *zimagi
        entrypoint: zimagi-worker
