config:
    # Core
    platform_name: default

    provision_domain: true

    cert_name: "@platform_name"
    cert_group: "@{platform_name}-cert"

    # Data
    data_group: "@{platform_name}-data"
    data_subnet_cidr_prefix: 28
    data_subnet_public_ip: false

    database_name: "@{platform_name}-database"
    database: "%%database:30"
    database_user: "%%database_user:30"
    database_password: "%%database_password:30"
    database_port: 5432

    queue_name: "@{platform_name}-queue"
    queue_type: redis
    queue_port: 6379

    data_firewall_prefix: "data-"

    # Service
    service_cli_host_name: default
    service_api_subnet_cidr_prefix: 26
    service_api_subnet_public_ip: true
    service_worker_subnet_cidr_prefix: 26
    service_worker_subnet_public_ip: true

    service_name: "@{platform_name}-service"
    service_group: "@{platform_name}-service"
    service_command_name: "@{service_name}-command"
    service_command_group: "@{service_group}-command"
    service_command_port: 5123
    service_command_external_port: 5123
    service_command_count: 1
    service_command_manifest: https://raw.githubusercontent.com/zimagi/host/master/docker-compose.command.yml
    service_data_name: "@{service_name}-data"
    service_data_group: "@{service_group}-data"
    service_data_port: 5323
    service_data_external_port: 443
    service_data_count: 1
    service_data_manifest: https://raw.githubusercontent.com/zimagi/host/master/docker-compose.data.yml
    service_worker_name: "@{service_name}-worker"
    service_worker_group: "@{service_group}-worker"
    service_worker_count: 1
    service_worker_manifest: https://raw.githubusercontent.com/zimagi/host/master/docker-compose.worker.yml

    service_internal_firewall_prefix: "internal-"
    service_external_firewall_prefix: "external-"

    service_lib_dir: /usr/local/lib/zimagi
    service_secret_key: "%%secret_key:50"
    service_allowed_hosts:
        - "*"

    service_user: "@CLI_ADMIN_USER"
    service_default_token: "@CLI_DEFAULT_ADMIN_TOKEN"
    service_parallel: "@CLI_PARALLEL"
    service_db_max_connections: 10
    service_thread_count: 10
    service_worker_concurrency: 5
    service_terraform_max_processes: 10
    service_ansible_max_processes: 10
    service_auto_migrate_timeout: 300
    service_auto_migrate_interval: 9000
    service_mutex_ttl_seconds: 300
    service_log_level: "@CLI_LOG_LEVEL"
    service_debug: "@CLI_DEBUG"
    service_core_module: "@CLI_CORE_MODULE"
    service_db_package_all_name: "@CLI_DB_PACKAGE_ALL_NAME"

    service_email_host:
    service_email_port: 25
    service_email_host_user: ""
    service_email_host_password: ""
    service_email_use_tls: true
    service_email_use_ssl: false
    service_email_ssl_certfile:
    service_email_ssl_keyfile:
    service_email_timeout:
    service_email_subject_prefix: "[@{platform_name}]:"
    service_email_use_localtime: true

group:
    "@cert_group":
    "@data_group":
    "@service_group":
        - "@service_command_group"
        - "@service_data_group"
        - "@service_worker_group"
