config:
    platform_name: default # (required)
    host_type: dev
    deploy_zimagi: true

    service_cli_host_name: "@platform_name"

    service_name: "@{platform_name}-service"
    service_command_name: "@{service_name}-command"
    service_data_name: "@{service_name}-data"
    service_worker_name: "@{service_name}-worker"

    # Group
    data_group: "@{platform_name}-data"

    service_group: "@{platform_name}-service"
    service_command_group: "@{service_group}-command"
    service_data_group: "@{service_group}-data"
    service_worker_group: "@{service_group}-worker"

    # Domain
    provision_domain: true

    # Network
    host_type_network_cidr_prefix:
        dev: 28
        qa: 24
        prod: 16

    data_subnet_prefix: "data-"
    worker_subnet_prefix: "worker-"
    service_subnet_prefix: "service-"

    # Firewall
    data_firewall_prefix: "data-"

    service_internal_firewall_prefix: "internal-"
    service_external_firewall_prefix: "external-"

    # Database
    database_name: "@{platform_name}-database"
    database: "%%database:30"
    database_user: "%%database_user:30"
    database_password: "%%database_password:30"
    database_port: 5432

    # In Memory Store (Queue & Cache)
    memory_store_name: "@{platform_name}-memory-store"
    memory_store_type: redis
    memory_store_port: 6379

    # Server
    service_command_port: 5123
    service_command_external_port: 5123
    service_command_count: 1
    service_command_manifest: https://raw.githubusercontent.com/zimagi/host/main/docker-compose.command.yml

    service_data_port: 5323
    service_data_external_port: 443
    service_data_count: 1
    service_data_manifest: https://raw.githubusercontent.com/zimagi/host/main/docker-compose.data.yml

    service_worker_count: 1
    service_worker_manifest: https://raw.githubusercontent.com/zimagi/host/main/docker-compose.worker.yml

    # Application
    service_data_dir: /var/local/zimagi
    service_lib_dir: /usr/local/lib/zimagi

    service_secret_key: "%%secret_key:50"
    service_allowed_hosts:
        - "*"

    service_user: "@CLI_ADMIN_USER"
    service_default_token: "@CLI_DEFAULT_ADMIN_TOKEN"
    service_parallel: "@CLI_PARALLEL"
    service_db_max_connections: 10
    service_thread_count: 10
    service_worker_concurrency: 5
    service_terraform_max_processes: 10
    service_ansible_max_processes: 10
    service_auto_migrate_timeout: 300
    service_auto_migrate_interval: 9000
    service_mutex_ttl_seconds: 300
    service_log_level: "@CLI_LOG_LEVEL"
    service_debug: "@CLI_DEBUG"
    service_core_module: "@CLI_CORE_MODULE"
    service_db_package_all_name: "@CLI_DB_PACKAGE_ALL_NAME"

    service_email_host:
    service_email_port: 25
    service_email_host_user: ""
    service_email_host_password: ""
    service_email_use_tls: true
    service_email_use_ssl: false
    service_email_ssl_certfile:
    service_email_ssl_keyfile:
    service_email_timeout:
    service_email_subject_prefix: "[@{platform_name}]:"
    service_email_use_localtime: true
