parents:
    - module: aws
      profile: config

    - config

config:
    # Domain
    domain_provider: route53

    # Network
    aws_networks:
        - us-east-1

    aws_subnet_zones:
        - b
        - c

    # Load Balancer
    aws_service_lb_timeout: 3600
    aws_service_lb_health_path: /status
    aws_service_lb_healthy_status: 200
    aws_service_lb_health_check_interval: 30
    aws_service_lb_health_timeout: 10
    aws_service_lb_healthy_threshold: 3
    aws_service_lb_unhealthy_threshold: 3
