parents:
    - module: aws
      profile: config

    - config

config:
    # Domain
    domain_provider: route53

    # Network
    aws_networks:
        - us-east-1

    aws_subnet_zones:
        - b
        - c

    aws_data_subnet_prefix: "data-"
    aws_worker_subnet_prefix: "worker-"
    aws_service_subnet_prefix: "service-"

    # Server
    aws_service_command_machine: t2.medium
    aws_service_command_tenancy: default
    aws_service_command_monitoring: true
    aws_service_command_ebs_optimized: false

    aws_service_data_machine: r5.large
    aws_service_data_tenancy: default
    aws_service_data_monitoring: true
    aws_service_data_ebs_optimized: false

    aws_service_worker_machine: r5.large
    aws_service_worker_tenancy: default
    aws_service_worker_monitoring: true
    aws_service_worker_ebs_optimized: false

    # Load Balancer
    aws_service_lb_timeout: 3600
    aws_service_lb_health_path: /status
    aws_service_lb_healthy_status: 200
    aws_service_lb_health_check_interval: 30
    aws_service_lb_health_timeout: 10
    aws_service_lb_healthy_threshold: 3
    aws_service_lb_unhealthy_threshold: 3
