parents:
    - aws/platform/config

config:
    # Network
    data_subnet_cidr_prefix: 24
    data_subnet_public_ip: false

    worker_subnet_cidr_prefix: 20
    worker_subnet_public_ip: false

    service_subnet_cidr_prefix: 20
    service_subnet_public_ip: true

    # Server
    aws_service_command_machine: t2.medium
    aws_service_command_tenancy: default
    aws_service_command_monitoring: true
    aws_service_command_ebs_optimized: false

    aws_service_data_machine: r5.large
    aws_service_data_tenancy: default
    aws_service_data_monitoring: true
    aws_service_data_ebs_optimized: false

    aws_service_worker_machine: r5.large
    aws_service_worker_tenancy: default
    aws_service_worker_monitoring: true
    aws_service_worker_ebs_optimized: false
