parents:
    - aws/config

config:
    # Network
    data_subnet_cidr_prefix: 24
    data_subnet_public_ip: false

    worker_subnet_cidr_prefix: 20
    worker_subnet_public_ip: false

    service_subnet_cidr_prefix: 20
    service_subnet_public_ip: true
